### ISSUE TITLE
 README.MD  javítás

### ISSUE THREAD

**Issue by krosza** [edemo/PDAnchor#2]
hogy lehet ezen javítani?

**Comment by magwas** [comment]
Pl. Így:
- a https://github.com/edemo/PDAnchor oldalon rányomsz jobb felül a fork gombra.
- a https://github.com/krosza/PDAnchor/blob/master/README.MD oldalon a "raw" "blame" "history" mellett jobbra megnyomod a ceruzát.
- megszerkeszted
- benyomod a "commit changes" gombot
- a https://github.com/krosza/PDAnchor oldalon ahol azt látod, hogy "This branch is 1 commit ahead of edemo:master.", mellette jobbra megnyomod a "Pull request" linket.
- megnyomod a "Create pull request" gombot
- megint megnyomod a "Create pull request" gombot
