### ISSUE TITLE
500 if ID is wrong

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDAnchor#22]

**Comment by Claymanus** [comment]
for example: <id>42345234</id>

**Comment by Claymanus** [comment]
érdekes, mert nem mindig csinálja

**Comment by Claymanus** [comment]
lsd még pdoauth 772 Krosza commentje

**Comment by magwas** [comment]
Az anchoron nem történt 500 december 27.-e óta. Az is akkor volt, amikor még konfiguráltam otthon.
Invalid.

**Comment by magwas** [comment]
# grep "raspberrypi apache" /var/log/messages* |awk '{split($13,p,"/");print $15, $12, p[2], $14}' |sort |uniq -c|sort -n
      1 "-" "-"  0
      1 206 "GET  HTTP/1.1"
      1 404 "GET admin HTTP/1.1"
      1 404 "GET apple-app-site-association HTTP/1.1"
      1 404 "GET .well-known HTTP/1.1"
      1 406 "GET anchor HTTP/1.1"
      1 "-" "-"  5893
      1 "-" "-"  6155
      2 304 "GET filesystem HTTP/1.1"
      2 404 "GET  HTTP/1.1"
      2 404 "HEAD admin HTTP/1.1"
      2 404 "HEAD index.php HTTP/1.1"
      5 404 "GET robots.txt HTTP/1.0"
      8 "-" "-"  137
      8 400 "GET  HTTP/1.0"
     27 301 "GET filesystem HTTP/1.1"
     55 200 "GET waiting.gif HTTP/1.1"
     67 403 "GET filesystem HTTP/1.1"
     76 404 "GET robots.txt HTTP/1.1"
    105 200 "GET icons HTTP/1.1"
    179 406 "POST anchor HTTP/1.1"
    199 200 "GET  HTTP/1.1"
    207 200 "POST anchor HTTP/1.1"
    210 404 "GET favicon.ico HTTP/1.1"
   3810 404 "GET filesystem HTTP/1.1"
   6268 200 "GET filesystem HTTP/1.1"

**Comment by magwas** [comment]
okay, it does exist in the master branch
